name: PinMyMetal
channels:
  - main
  - conda-forge
  - defaults
dependencies:
  - atomium=1.0.11
  - biopython=1.84
  - imbalanced-learn
  - joblib=1.2.0
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - numpy=1.23.5
  - pandas=2.1.4
  - pip=23.3.1
  - psycopg2=2.9.9
  - python=3.11.5
  - scikit-learn=1.3.0
  - tensorflow=2.12.0
  - tensorflow-base=2.12.0
  - tensorflow-estimator=2.12.0
  - termcolor=2.1.0
  - wget=1.21.4
